/*
* @(#)PageTypeEnum.java	Thu Feb 18 15:34:53 CST 2016
*
* Generated by com.ytsp.db.code.generator.EnumsCodeGenerator.
*/

package com.statistics.enums;


import com.ytsp.db.enums.base.BaseEnum;

/**
 * enum '页面类型'
 */
public enum LoginStatusEnum implements BaseEnum
{
	ISDirect_Login(1,"直接登录","直接登录"),BINDING_MOBILE(2,"绑定手机","绑定手机"),PROMPT_IFNO(3,"重要信息提示","重要信息提示");

	private Integer value;
	private String text;
	private String description;

	LoginStatusEnum(Integer value, String text, String description) {
		this.value = value;
		this.text = text;
		this.description = description;
	}

	public Integer getValue() {
		return this.value;
	}

	public String getText() {
		return this.text;
	}

	public String getDescription() {
		return this.description;
	}
	
	public static LoginStatusEnum valueOf(Integer value){
		LoginStatusEnum[] values = LoginStatusEnum.values();
		for(LoginStatusEnum e : values){
			if(e.getValue().intValue() == value){
				return e;
			}
		}
		return null;
	 }

}
